import localFont from 'next/font/local'
import "./globals.css";
import { Footer } from '@/components/Footer';
import { Navbar } from '@/components/Navbar';

const gmarkSansL = localFont({
  src: './fonts/GmarketSansTTFLight.ttf',
  weight: 'normal',
  style: 'normal',
})

const gmarkSansM = localFont({
  src: './fonts/GmarketSansTTFMedium.ttf',
  weight: 'normal',
  style: 'normal',
})

const gmarkSansB = localFont({
  src: './fonts/GmarketSansTTFBold.ttf',
  weight: 'normal',
  style: 'normal',
})


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body
        className={`${gmarkSansM.className} antialiased`}
      >
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
